# Generated by Django 5.2.7 on 2025-11-19 10:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('profile_pic', models.ImageField(blank=True, help_text='Upload a professional profile picture', null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('address', models.CharField(help_text='Full address', max_length=200)),
                ('mobile', models.CharField(help_text='Contact number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Neurologists', 'Neurologists'), ('Oncologists', 'Oncologists'), ('Ophthalmologists', 'Ophthalmologists'), ('Orthopedic Surgeons', 'Orthopedic Surgeons'), ('Pediatricians', 'Pediatricians'), ('Psychiatrists', 'Psychiatrists'), ('Radiologists', 'Radiologists'), ('Urologists', 'Urologists')], db_index=True, default='Cardiologist', help_text='Medical specialization', max_length=50)),
                ('status', models.BooleanField(db_index=True, default=False, help_text='Approved status')),
                ('qualifications', models.TextField(blank=True, help_text='Educational qualifications and certifications', null=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of medical practice')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Consultation fee in USD', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('profile_pic', models.ImageField(blank=True, help_text='Upload profile picture', null=True, upload_to='profile_pic/PatientProfilePic/')),
                ('address', models.CharField(help_text='Full address', max_length=200)),
                ('mobile', models.CharField(help_text='Contact number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('symptoms', models.TextField(help_text='Describe your symptoms')),
                ('admit_date', models.DateField(auto_now_add=True, help_text='Date of admission')),
                ('status', models.BooleanField(db_index=True, default=False, help_text='Approved/Admitted status')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group', max_length=5)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('assignedDoctorId', models.PositiveIntegerField(blank=True, editable=False, help_text='Legacy field - use assigned_doctor instead', null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, help_text='Assigned doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospital.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-admit_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of appointment')),
                ('description', models.TextField(help_text='Reason for appointment', max_length=1000)),
                ('status', models.BooleanField(db_index=True, default=False, help_text='Approval status')),
                ('patientId', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('doctorId', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('patientName', models.CharField(blank=True, editable=False, max_length=100)),
                ('doctorName', models.CharField(blank=True, editable=False, max_length=100)),
                ('appointmentDate', models.DateField(blank=True, editable=False, null=True)),
                ('doctor', models.ForeignKey(help_text='Doctor for appointment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.doctor')),
                ('patient', models.ForeignKey(help_text='Patient for appointment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('admit_date', models.DateField(help_text='Date of admission')),
                ('release_date', models.DateField(help_text='Date of discharge')),
                ('day_spent', models.PositiveIntegerField(help_text='Number of days in hospital')),
                ('room_charge', models.DecimalField(decimal_places=2, help_text='Room charges per day', max_digits=10)),
                ('medicine_cost', models.DecimalField(decimal_places=2, help_text='Total medicine cost', max_digits=10)),
                ('doctor_fee', models.DecimalField(decimal_places=2, help_text='Doctor consultation fee', max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, help_text='Other miscellaneous charges', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total bill amount', max_digits=10)),
                ('patientId', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('patientName', models.CharField(blank=True, editable=False, max_length=100)),
                ('assignedDoctorName', models.CharField(blank=True, editable=False, max_length=100)),
                ('address', models.CharField(blank=True, editable=False, max_length=200)),
                ('mobile', models.CharField(blank=True, editable=False, max_length=20)),
                ('symptoms', models.CharField(blank=True, editable=False, max_length=500)),
                ('admitDate', models.DateField(blank=True, editable=False, null=True)),
                ('releaseDate', models.DateField(blank=True, editable=False, null=True)),
                ('daySpent', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('roomCharge', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('medicineCost', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('doctorFee', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('OtherCharge', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('assigned_doctor', models.ForeignKey(help_text='Doctor who treated the patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_records', to='hospital.doctor')),
                ('patient', models.ForeignKey(help_text='Patient being discharged', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_records', to='hospital.patient')),
            ],
            options={
                'verbose_name': 'Patient Discharge Detail',
                'verbose_name_plural': 'Patient Discharge Details',
                'ordering': ['-release_date'],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['department', 'status'], name='hospital_do_departm_0440de_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status', 'assigned_doctor'], name='hospital_pa_status_5fc5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='hospital_ap_appoint_82af2e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='hospital_ap_doctor__8632ec_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='hospital_ap_patient_fafeb8_idx'),
        ),
    ]
